export const SEARCH_CLASSROOM = 'SEARCH_CLASSROOM';
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const ADD_CLASSROOM = 'ADD_CLASSROOM';
export const DELETE_CLASSROOM = 'DELETE_CLASSROOM';
export const CHANGE_IS_OPEN = 'CHANGE_IS_OPEN';
export const EDIT_DETAILS = 'EDIT_DETAILS';
export const CLEAR_EDIT = 'CLEAR_EDIT';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const GET_CLASSROOM = 'GET_CLASSROOM';
export const CLASSROOM_ERROR = 'CLASSROOM_ERROR';

export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_REGISTER = 'FAIL_REGISTER';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const SET_TEACHER = 'SET_TEACHER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_CLASSROOM_BY_ID = 'GET_CLASSROOM_BY_ID';

export const STORE_EXAM = 'STORE_EXAM';

export const GET_STUDENTS = 'GET_STUDENTS';

export const CLEAR_SEARCH_S = 'CLEAR_SEARCH_S';

export const SEARCH_STUDENTS_NAME = 'SEARCH_STUDENTS_NAME';
export const SEARCH_STUDENTS_ID = 'SEARCH_STUDENTS_ID';

export const CHECKED_STATUS = 'CHECKED_STATUS';


export const GET_EXAMS = 'GET_EXAMS';
export const SEARCH_EXAM_BY_NAME = 'SEARCH_EXAM_BY_NAME';
export const CLEAR_EXAM_BY_NAME = 'CLEAR_EXAM_BY_NAME';



